---
- hosts: all
  become: yes
  tasks:
    - name: Mise à jour des paquets
      apt:
        update_cache: yes

    - name: Installation d'Apache
      apt:
        name: apache2
        state: present

    - name: Copie du fichier de la page web
      copy:
        content: "<html><body><h1>Bienvenue sur le site web Ansible</h1></body></html>"
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
